azs:
- name: z1
  cloud_properties:
    datacenters:
    - name: {{.BoshVsphereVcenterDc}}
      clusters:
        - {{.BoshVsphereVcenterCluster}}: {}

vm_types:
- name: default
  cloud_properties:
    ram: 2048
    cpu: 1
    disk: 5120

networks:
- name: default
  type: manual
  subnets:
  - range: {{.Network1.VCenterCIDR}}
    reserved: [{{.Network1.ReservedRange}}]
    gateway: {{.Network1.VCenterGateway}}
    az: z1
    cloud_properties:
      name: {{.Network1.VCenterVLAN}}

compilation:
  workers: 2
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: default