---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-ubuntu-chroot

inputs:
  - name: bosh-linux-stemcell-builder-versions-json
  - name: ubuntu-trusty-tarball

run:
  path: bosh-linux-stemcell-builder-versions-json/ci/tasks/write-version.sh
