azs:
- name: z1
  cloud_properties:
    datacenters:
    - name: ((vcenter_dc))
      clusters:
        - ((vcenter_cluster)): {}

vm_types:
- name: default
  cloud_properties:
    ram: 2048
    cpu: 1
    disk: 5120

networks:
- name: default
  type: manual
  subnets:
  - range: ((internal_cidr))
    reserved: ((internal_reserved))
    gateway: ((internal_gw))
    az: z1
    cloud_properties:
      name: ((internal_vcenter_vlan))}

compilation:
  workers: 2
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: default